---
- name: Master
  hosts: all

  tasks:
    - name: Hello world
      debug:
        msg: "Hello, world!"

    - name: Install Apache
      sudo: true
      apt:
        name: apache2
        state: present

    - name: Install php
      sudo: true
      apt:
        name: php
        state: present

    - name: Install Vim
      become: yes
      apt:
        name: vim
        state: present
        update_cache: true

    - name: Install mc
      become: yes
      apt:
        name: mc
        state: present
        update_cache: true

    

    - name: CURL simple download file2
      sudo: true
      uri:
        url: https://raw.githubusercontent.com/MaxChernoshey/itacademy-devops-files/master/02-tools/index.php
        dest: /var/www/html

          
    - name:  delete file  
      sudo: true
      file:
        path: /var/www/html/index.html
        state: absent

    - name: Restart service httpd, in all cases
      sudo: true
      service:
        name: apache2
        state: reloaded