
Vagrant.configure("2") do |config|
  
  config.vm.box = "chernoshey/centos8s"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 81, host: 8081, host_ip: "127.0.0.1"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
  end
 
  config.vm.provision "shell", inline: <<-SHELL
    
    systemctl stop firewalld
    systemctl disable firewalld
    
    echo "Listen 81" >> /etc/httpd/conf/httpd.conf
    echo "<VirtualHost *:81>
      DocumentRoot /var/www/php
    </VirtualHost>" >> /etc/httpd/conf.d/1.conf
    mkdir /var/www/php
    wget https://raw.githubusercontent.com/MaxChernoshey/itacademy-devops-files/master/02-tools/index.html -O /var/www/html/index.html
    wget https://raw.githubusercontent.com/MaxChernoshey/itacademy-devops-files/master/02-tools/index.php -O /var/www/php/index.php
    systemctl reload httpd.service
  SHELL
end
