# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian10"

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 81, host: 8081, host_ip: "127.0.0.1"
  
  config.vm.synced_folder  ".", "/vagrant", disabled: false
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
  end

  config.vm.define "master", primary: true do |master|
    master.vm.network "private_network", ip: "10.0.2.16"

       
    master.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbook.yaml"
    end
  end  
end
  
