Vagrant.configure("2") do |config|
    config.vm.box = "generic/debian11"
    config.vm.synced_folder  ".", "/vagrant", disabled: false

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus   = 1
    end

    config.vm.define "jenkins.vm", primary: true do |master|
        master.vm.network "private_network", ip: "192.168.33.62"
        master.vm.hostname = "jenkins.vm"
        master.vm.provider("virtualbox") { |vb| vb.memory = 1024 }

        master.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "jenkins.yaml"
            ansible.become = true
            ansible.compatibility_mode = "2.0"
#           ansible.limit = 'all'
#            ansible.inventory_path = "inventory"
        end
    end
    
end
