
Vagrant.configure("2") do |config|
  
  config.vm.box = "generic/centos8s"
  config.ssh.insert_key = false
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
  end
 
  config.vm.provision "shell", inline: <<-SHELL
    yum install -y httpd
    yum install -y php
    systemctl start httpd.service
    systemctl enable httpd.service
  SHELL
end